language: ruby
rvm:
  - 2.0
  - 2.4
  - 2.5
  - ruby-head
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec --require spec_helper --color --format documentation spec
